### ISSUE TITLE
Generate templates: can not install yaml module

### ISSUE THREAD

**Issue by lukas-vlcek** [BitScoutOrg/elasticsearch-templates#15]
@t0ffel Anton, I am trying to regenerate templates after updating `skeleton.json` but I am running into some Python issue:

```
$ pwd
<elasticsearch-templates>/scripts

$ python --version
Python 2.7.12

$ python generate_template.py viaq-openshift com.redhat.viaq-openshift
Traceback (most recent call last):
  File "generate_template.py", line 14, in <module>
    import yaml
ImportError: No module named yaml

$ python -m pip install yaml
Collecting yaml
  Could not find a version that satisfies the requirement yaml (from versions: )
No matching distribution found for yaml
```

Do I need specific Python version or anything like that?

**Comment by richm** [comment]
@lukas-vlcek https://pypi.python.org/pypi?%3Aaction=search&term=yaml&submit=search
Try pyaml

```
pip install pyaml
```

Works fine without pip on Fedora 24 - I'm using PyYAML-3.11-12.fc24.x86_64

**Comment by lukas-vlcek** [comment]
This helped for Mac OS as well.

**Comment by Fourier1** [comment]
i can not install yaml i use the python2.7 version
pip install yaml
sudo apt-get install yaml

**Comment by Fourier1** [comment]
solution
$  pip install pyaml

**Comment by KevinDCruz** [comment]
Virtual Environment Setting 

```
Python version: 3.6.3
Operating system: Windows, 64 Bits
```
 

Keras was not installing because of pyyaml setting not meeting up for python 3.6. I already had Anaconda installed in a different virtualenv with keras working fine (pyyaml module installed). I just used conda install pyyaml instead of pip and it got installed, thereby using `pip install keras` to install the keras library in my new virtual environment.

if you have anaconda installed already, try using

`conda install yaml
`

and see if it works. It worked for me!
